[package]
name = "alic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc="*"

[dependencies]
defer = "0.2.1"
tree-sitter = "~0.22.5"
tree-sitter-ali = { path = "./tree-sitter-ali" }

